// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_mkUOmBlqXAIxMYqy2q7RPFzlpJPVo1w',
    appId: '1:120756727705:web:18271c501611f4c7caed08',
    messagingSenderId: '120756727705',
    projectId: 'dreamventz2026',
    authDomain: 'dreamventz2026.firebaseapp.com',
    storageBucket: 'dreamventz2026.firebasestorage.app',
    measurementId: 'G-Z65KC3JVP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO4dk41aYdWvMEwU1qo67DrGNxkwj1B44',
    appId: '1:120756727705:android:b05673dc01973724caed08',
    messagingSenderId: '120756727705',
    projectId: 'dreamventz2026',
    storageBucket: 'dreamventz2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCgXRK48ZdxWfK-S-xOuprg5zLr4GZgz4',
    appId: '1:120756727705:ios:3c244576b5d86714caed08',
    messagingSenderId: '120756727705',
    projectId: 'dreamventz2026',
    storageBucket: 'dreamventz2026.firebasestorage.app',
    iosBundleId: 'com.example.dreamventz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCgXRK48ZdxWfK-S-xOuprg5zLr4GZgz4',
    appId: '1:120756727705:ios:3c244576b5d86714caed08',
    messagingSenderId: '120756727705',
    projectId: 'dreamventz2026',
    storageBucket: 'dreamventz2026.firebasestorage.app',
    iosBundleId: 'com.example.dreamventz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_mkUOmBlqXAIxMYqy2q7RPFzlpJPVo1w',
    appId: '1:120756727705:web:efbcddae2c195931caed08',
    messagingSenderId: '120756727705',
    projectId: 'dreamventz2026',
    authDomain: 'dreamventz2026.firebaseapp.com',
    storageBucket: 'dreamventz2026.firebasestorage.app',
    measurementId: 'G-WCQ9PPH6KL',
  );

}